# nixpacks.toml
providers = ["node"]

[phases.setup]
# npm을 별도 패키지로 깔지 말고 Node 20만 설치
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci || npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
