import Link from 'next/link'
import { Button } from '@/components/ui/Button'

export default function Hero({ lang, dict }) {
  return (
    <section className="relative bg-gradient-to-br from-pink-50 to-purple-50 py-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center">
          <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
            {dict.hero.title}
          </h1>
          <p className="text-xl md:text-2xl text-gray-600 mb-8 max-w-3xl mx-auto">
            {dict.hero.subtitle}
          </p>
          <p className="text-lg text-gray-500 mb-12 max-w-2xl mx-auto">
            {dict.hero.description}
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              as={Link}
              href={`/${lang}/contact`}
              variant="primary"
              size="lg"
            >
              {dict.hero.bookNow}
            </Button>
            <Button 
              as={Link}
              href={`/${lang}/services`}
              variant="outline"
              size="lg"
            >
              {dict.hero.viewServices}
            </Button>
          </div>
        </div>

        {/* Features Grid */}
        <div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center p-6 bg-white rounded-lg shadow-sm">
            <div className="text-4xl mb-4">🎨</div>
            <h3 className="text-xl font-semibold mb-2">AI Nail Art</h3>
            <p className="text-gray-600">Custom designs generated by artificial intelligence</p>
          </div>
          <div className="text-center p-6 bg-white rounded-lg shadow-sm">
            <div className="text-4xl mb-4">💅</div>
            <h3 className="text-xl font-semibold mb-2">Professional Care</h3>
            <p className="text-gray-600">Expert nail technicians with premium products</p>
          </div>
          <div className="text-center p-6 bg-white rounded-lg shadow-sm">
            <div className="text-4xl mb-4">📱</div>
            <h3 className="text-xl font-semibold mb-2">Online Booking</h3>
            <p className="text-gray-600">Easy appointment scheduling system</p>
          </div>
        </div>
      </div>
    </section>
  )
}