import Link from 'next/link'

export default async function ServicesPage({ params }) {
  const { lang } = await params

  const services = [
    {
      id: 1,
      name: lang === 'ko' ? 'AI 네일 아트' : 'AI Nail Art',
      description: lang === 'ko' 
        ? '인공지능이 생성하는 독창적인 네일 디자인'
        : 'Unique nail designs generated by artificial intelligence',
      price: '$50-80',
      duration: '90 min',
      image: '🎨'
    },
    {
      id: 2,
      name: lang === 'ko' ? '클래식 매니큐어' : 'Classic Manicure',
      description: lang === 'ko'
        ? '기본적인 네일 케어와 폴리쉬 서비스'
        : 'Basic nail care and polish service',
      price: '$25-35',
      duration: '45 min',
      image: '💅'
    },
    {
      id: 3,
      name: lang === 'ko' ? '젤 네일' : 'Gel Nails',
      description: lang === 'ko'
        ? '오래 지속되는 젤 폴리쉬'
        : 'Long-lasting gel polish application',
      price: '$40-55',
      duration: '60 min',
      image: '✨'
    }
  ]

  return (
    <div className="min-h-screen bg-gradient-to-br from-pink-50 to-purple-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="text-center mb-12">
          <Link 
            href={`/${lang}`}
            className="inline-block bg-pink-600 text-white px-4 py-2 rounded-lg mb-6 hover:bg-pink-700 transition-colors"
          >
            ← {lang === 'ko' ? '홈으로' : 'Back to Home'}
          </Link>
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            {lang === 'ko' ? '서비스' : 'Services'}
          </h1>
          <p className="text-xl text-gray-600">
            {lang === 'ko' 
              ? '다양한 네일 케어 서비스를 제공합니다'
              : 'Professional nail care services tailored for you'
            }
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {services.map((service) => (
            <div key={service.id} className="bg-white rounded-lg shadow-lg p-6 hover:shadow-xl transition-shadow">
              <div className="text-6xl text-center mb-4">{service.image}</div>
              <h3 className="text-xl font-semibold mb-2 text-center">{service.name}</h3>
              <p className="text-gray-600 mb-4 text-center">{service.description}</p>
              <div className="flex justify-between items-center mb-4">
                <span className="text-pink-600 font-semibold">{service.price}</span>
                <span className="text-gray-500">{service.duration}</span>
              </div>
              <button className="w-full bg-pink-600 text-white py-2 rounded-lg hover:bg-pink-700 transition-colors">
                {lang === 'ko' ? '예약하기' : 'Book Now'}
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}